# Generated by Django 4.2.7 on 2023-11-24 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_voters_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidates',
            old_name='description',
            new_name='manifesto',
        ),
    ]
