# Generated by Django 4.2.7 on 2023-11-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_candidates_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
