# Generated by Django 4.2.7 on 2023-11-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_alter_candidates_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
